version: "3.8"


   
services:
  db:
    image: postgres:13
    hostname: db
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - django_network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    hostname: nginx
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./docxtopdf/static:/static
      - ./docxtopdf/media:/media
    ports:
      - "80:80"
    networks:
      main:
        aliases:
          - nginx

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      main:
        aliases:
          - rabbitmq


  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: celery
    volumes:
      - ./docxtopdf/media:/media
    depends_on:
      - rabbitmq
    links:
      - rabbitmq:rabbitmq
    networks:
      main:
        aliases:
          - celery
    


  web:
    build: .
    hostname: web
    command: bash -c "sleep 10 && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn docxtopdf.wsgi -w 4 --bind 0.0.0.0:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 8000
    depends_on:
      - rabbitmq
      - db
    links:
      - db:db
      - rabbitmq:rabbitmq
    volumes:
      - ./docxtopdf/media:/media
    networks:
      main:
        aliases:
          - web
   

networks:
  main:


