version: "3.8"


   
services:
  db:
    image: postgres:13
    hostname: db
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672


  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: celery
    volumes:
      - .:/app
    command: bash -c "cd docxtopdf  && celery -A docxtopdf worker -l INFO"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq:rabbitmq


  web:
    build: .
    command: bash -c "cd docxtopdf && sleep 10 && python manage.py migrate && 
                      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    links:
      - db:db
      - rabbitmq:rabbitmq
   

