version: "3.8"


   
services:
  db:
    image: postgres:13
    hostname: db
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - django_network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    hostname: nginx
    container_name: nginx
    volumes:
      - ./docxtopdf:/docxtopdf
    ports:
      - "80:80"
    networks:
      main:
        aliases:
          - django_network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      main:
        aliases:
          - django_network


  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: celery
    volumes:
      - .:/app
    command: bash -c "cd docxtopdf  && celery -A docxtopdf worker -l INFO"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq:rabbitmq
    networks:
      main:
        aliases:
          - django_network
    


  web:
    build: .
    hostname: web
    command: bash -c "cd docxtopdf && sleep 10 && python manage.py migrate && gunicorn docxtopdf.wsgi -w 4 --bind 0.0.0.0:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 8000
    depends_on:
      - rabbitmq
      - db
      - nginx
    links:
      - db:db
      - rabbitmq:rabbitmq
    networks:
      main:
        aliases:
          - django_network
   

networks:
  main:
  

