# Generated by Django 3.2.4 on 2022-03-10 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDocxPdf',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.FilePathField()),
            ],
        ),
    ]
