# Generated by Django 3.2.4 on 2022-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocxpdf',
            name='filepathpdf',
            field=models.FilePathField(default=''),
        ),
    ]
