# Generated by Django 4.0.3 on 2022-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_filedocxpdf_filepathpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocxpdf',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
