# Generated by Django 4.0.3 on 2022-03-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_filedocxpdf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocxpdf',
            name='filename',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='filedocxpdf',
            name='filepath',
            field=models.FilePathField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='filedocxpdf',
            name='type',
            field=models.CharField(max_length=1024),
        ),
    ]
