# Generated by Django 4.0.3 on 2022-03-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_alter_filedocxpdf_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocxpdf',
            name='filepathpdf',
            field=models.FilePathField(default='', max_length=1024),
        ),
    ]
